import Link from "next/link";
import { CheckCircle2, Clock3, CreditCard, QrCode } from "lucide-react";
import { notFound } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { formatRupiah } from "@/lib/utils";
import { MarketplaceShell } from "@/components/mp/marketplace-shell";

type Params = { order_id: string };
export default async function PaymentPage({ params }: { params: Promise<Params> }) { const { order_id } = await params; const session = await auth(); const userId = (session?.user as { id?: string } | undefined)?.id; const order = userId ? await prisma.orderMP.findFirst({ where: { id: order_id, buyerId: userId }, include: { pembayaran: true } }) : null; if (!order) notFound(); const payment = order.pembayaran; return <MarketplaceShell><main className="mx-auto max-w-xl px-4 py-12 md:px-8"><div className="text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#e7f8ef] text-[#009a49]"><Clock3 className="h-8 w-8" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.16em] text-[#168bc3]">Pembayaran</p><h1 className="mt-2 text-3xl font-extrabold">Selesaikan pembayaran</h1><p className="mt-2 text-sm text-[#82919a]">Nomor pesanan {order.nomorOrder}</p></div><section className="mt-8 rounded-2xl border border-[#dce4e8] bg-white p-6 text-center"><p className="text-xs text-[#82919a]">Total yang harus dibayar</p><p className="mt-2 text-3xl font-extrabold text-[#e53935]">{formatRupiah(Number(order.totalBayar))}</p>{payment?.metode === "QRIS" ? <div className="mt-6 rounded-xl bg-[#f7f9fa] p-8"><QrCode className="mx-auto h-20 w-20 text-[#26343f]" /><p className="mt-3 text-xs text-[#53616d]">QRIS akan tampil setelah callback PayLabs tersedia.</p></div> : <div className="mt-6 rounded-xl bg-[#f7f9fa] p-5 text-left"><div className="flex items-center gap-3"><CreditCard className="h-5 w-5 text-[#168bc3]" /><span className="text-xs font-bold">Virtual Account</span></div><p className="mt-4 text-sm text-[#53616d]">Nomor VA dan instruksi bank akan diisi oleh integrasi PayLabs.</p></div>}<div className="mt-5 flex items-center justify-center gap-2 text-xs font-semibold text-[#009a49]"><CheckCircle2 className="h-4 w-4" />Pesanan tersimpan, menunggu pembayaran</div></section><Link href={`/pesanan/${order.id}`} className="mt-5 flex justify-center text-xs font-bold text-[#168bc3]">Lihat detail pesanan</Link></main></MarketplaceShell>; }
