"use client";

import { Check, ExternalLink, FileText, Landmark, MapPin, Package, ShieldCheck, Trash2, UserRound, Warehouse, X } from "lucide-react";
import { useState } from "react";

type Warehouse = { id: string; nama: string; alamatLengkap: string; provinsi: string; kabupatenKota: string; kecamatan: string; desa?: string | null; kodePos?: string | null };
type BankAccount = { id: string; bankNama: string; nomorRekening: string; namaPemilik: string; utama: boolean };
type Profile = { namaToko?: string; namaUsaha?: string; alamatLengkap?: string; provinsi?: string; kabupatenKota?: string; kecamatan?: string; desa?: string | null; kodePos?: string | null; noNib?: string | null; noNpwp?: string | null; dokumenNibUrl?: string | null; dokumenNpwpUrl?: string | null; gudang: Warehouse[]; rekening: BankAccount[] };
type Account = { id: string; name: string | null; email: string; role: "TOKO" | "DISTRIBUTOR"; statusAkun: string; reviewStatus?: string; telepon: string | null; createdAt: string; tokoProfile?: Profile | null; distributorProfile?: Profile | null };

const statusLabels: Record<string, string> = { MENUNGGU_VERIFIKASI: "Menunggu Review", AKTIF: "Aktif", DITOLAK: "Ditolak", NONAKTIF: "Nonaktif" };

export default function ScmAccountReviewDrawer({ account, onClose, onStatus, onDelete }: { account: Account; onClose: () => void; onStatus: (account: Account, status: string) => void; onDelete: () => void }) {
  const [documentError, setDocumentError] = useState("");
  const profile = account.tokoProfile || account.distributorProfile;
  const businessName = profile?.namaToko || profile?.namaUsaha || "Akun SCM";
  const address = [profile?.alamatLengkap, profile?.desa, profile?.kecamatan, profile?.kabupatenKota, profile?.provinsi, profile?.kodePos].filter(Boolean).join(", ");
  const isPending = account.statusAkun === "MENUNGGU_VERIFIKASI";

  return <div className="fixed inset-0 z-50 bg-slate-950/45 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-labelledby="review-drawer-title">
    <button className="absolute inset-0 cursor-default" onClick={onClose} aria-label="Tutup detail akun" />
    <aside className="absolute right-0 top-0 flex h-full w-full max-w-2xl flex-col bg-slate-50 shadow-2xl">
      <header className="sticky top-0 z-10 border-b border-slate-200 bg-white px-6 py-5 md:px-8">
        <div className="flex items-start justify-between gap-5">
          <div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full bg-sky-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-sky-700">{account.role}</span><Status status={account.reviewStatus || account.statusAkun} /></div><h2 id="review-drawer-title" className="truncate text-xl font-extrabold text-slate-900">{businessName}</h2><p className="mt-1 text-sm text-slate-500">Review registrasi dan kelengkapan akun mitra</p></div>
          <button onClick={onClose} className="shrink-0 rounded-lg p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700" aria-label="Tutup drawer"><X className="h-5 w-5" /></button>
        </div>
      </header>

      <div className="flex-1 overflow-y-auto px-6 py-6 md:px-8">
        <div className="space-y-5">
          <Section icon={<UserRound className="h-4 w-4" />} title="Informasi Akun" description="Data pemilik dan kontak utama"><div className="grid gap-4 sm:grid-cols-2"><Detail label="Nama PIC" value={account.name || "Belum diisi"} /><Detail label="Email" value={account.email} /><Detail label="Nomor Telepon" value={account.telepon || "Belum diisi"} /><Detail label="Status" value={statusLabels[account.statusAkun] || account.statusAkun} /></div></Section>
          <Section icon={<MapPin className="h-4 w-4" />} title="Alamat Utama" description="Alamat operasional yang diambil dari registrasi"><Detail label="Alamat lengkap" value={address || "Belum dilengkapi"} /></Section>
          <Section icon={<FileText className="h-4 w-4" />} title="Legalitas" description="Dokumen yang diperiksa sebelum approval"><div className="grid gap-3 sm:grid-cols-2"><Document label="NIB" number={profile?.noNib} path={profile?.dokumenNibUrl} onOpen={setDocumentError} /><Document label="NPWP" number={profile?.noNpwp} path={profile?.dokumenNpwpUrl} onOpen={setDocumentError} /></div>{documentError && <p className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-xs font-medium text-red-700">{documentError}</p>}</Section>
          <Section icon={<Package className="h-4 w-4" />} title="Operasional" description="Data pendukung aktivitas SCM"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Gudang terdaftar" value={`${profile?.gudang.length || 0} / 3`} /><Metric label="Rekening terdaftar" value={`${profile?.rekening.length || 0}`} /></div><div className="mt-4 space-y-3">{(profile?.gudang || []).map((warehouse) => <div key={warehouse.id} className="rounded-lg border border-slate-200 p-4"><div className="flex items-center gap-2"><Warehouse className="h-4 w-4 text-slate-500" /><p className="text-sm font-bold text-slate-700">{warehouse.nama}</p></div><p className="mt-2 text-xs leading-relaxed text-slate-600">{[warehouse.alamatLengkap, warehouse.desa, warehouse.kecamatan, warehouse.kabupatenKota, warehouse.provinsi, warehouse.kodePos].filter(Boolean).join(", ") || "Alamat belum lengkap"}</p></div>)}{(profile?.rekening || []).map((account) => <div key={account.id} className="flex items-start gap-3 rounded-lg border border-slate-200 p-4"><Landmark className="mt-0.5 h-4 w-4 text-slate-500" /><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-slate-700">{account.bankNama}</p>{account.utama && <span className="rounded-full bg-sky-50 px-2 py-1 text-[10px] font-bold text-sky-700">UTAMA</span>}</div><p className="mt-1 text-xs text-slate-600">{account.nomorRekening} · {account.namaPemilik}</p></div></div>)}</div></Section>
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div><p className="text-sm font-bold text-amber-900">Catatan review</p><p className="mt-1 text-xs leading-relaxed text-amber-800">Pastikan nama PIC, alamat, nomor legalitas, dan file PDF sudah sesuai sebelum akun diaktifkan.</p></div></div></div>
        </div>
      </div>

      <footer className="sticky bottom-0 border-t border-slate-200 bg-white px-6 py-4 md:px-8"><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-between"><div className="flex flex-wrap gap-2"><button onClick={onClose} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600 transition hover:bg-slate-50">Tutup</button><button onClick={onDelete} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700 transition hover:bg-red-50"><Trash2 className="h-4 w-4" /> Hapus Akun</button></div><div className="flex flex-col gap-2 sm:flex-row">{!isPending && <button onClick={() => onStatus(account, "NONAKTIF")} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700 transition hover:bg-slate-100">Nonaktifkan</button>}{isPending && <button onClick={() => onStatus(account, "DITOLAK")} className="rounded-lg border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700 transition hover:bg-red-50">Tolak</button>}<button onClick={() => onStatus(account, "AKTIF")} className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-5 py-2.5 text-sm font-bold text-white transition hover:bg-emerald-700"><Check className="h-4 w-4" /> {isPending ? "Approve Akun" : "Aktifkan Akun"}</button></div></div></footer>
    </aside>
  </div>;
}

function Section({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-start gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-600">{icon}</span><div><h3 className="text-sm font-bold text-slate-900">{title}</h3><p className="mt-0.5 text-xs text-slate-500">{description}</p></div></div>{children}</section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 break-words text-sm font-medium leading-relaxed text-slate-700">{value}</p></div>; }
function Document({ label, number, path, onOpen }: { label: string; number?: string | null; path?: string | null; onOpen: (message: string) => void }) { const [opening, setOpening] = useState(false); const uploaded = Boolean(path); const openDocument = async () => { if (!path) return; const newTab = window.open("about:blank", "_blank"); if (!newTab) { onOpen("Tab baru diblokir browser. Izinkan pop-up untuk membuka dokumen."); return; } setOpening(true); onOpen(""); const response = await fetch(`/api/admin/scm/documents?path=${encodeURIComponent(path)}`); const data = await response.json(); if (!response.ok || !data.url) { newTab.close(); onOpen("Dokumen tidak dapat dibuka saat ini."); setOpening(false); return; } newTab.location.href = data.url; setOpening(false); }; return <div className="rounded-lg border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-bold text-slate-700">{label}</p><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${uploaded ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{uploaded ? "File tersedia" : "Belum ada file"}</span></div><p className="mt-2 text-xs text-slate-500">Nomor: {number || "Belum diisi"}</p>{uploaded && <button onClick={openDocument} disabled={opening} className="mt-3 inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 transition hover:border-sky-400 hover:text-sky-700 disabled:opacity-50"><ExternalLink className="h-3.5 w-3.5" />{opening ? "Membuka..." : "Buka dokumen"}</button>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-lg font-extrabold text-slate-800">{value}</p></div>; }
function Status({ status }: { status: string }) { const color = status === "AKTIF" ? "bg-emerald-100 text-emerald-700" : status === "DITOLAK" ? "bg-red-100 text-red-700" : status === "NONAKTIF" ? "bg-slate-200 text-slate-700" : status === "BELUM_LENGKAP" ? "bg-slate-100 text-slate-600" : "bg-amber-100 text-amber-700"; const label = status === "BELUM_LENGKAP" ? "Belum Submit Dokumen" : statusLabels[status] || status; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${color}`}>{label}</span>; }
