import type { Metadata } from "next";
import { MapPin, Store, Truck } from "lucide-react";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { MarketplaceShell } from "@/components/mp/marketplace-shell";
import { ProductCard } from "@/components/mp/product-card";

type Params = { slug: string };
export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> { const { slug } = await params; const store = await prisma.tokoProfile.findUnique({ where: { slug }, select: { namaToko: true, deskripsi: true, kabupatenKota: true } }); return { title: store?.namaToko ?? "Toko Lokal", description: store?.deskripsi ?? `Belanja dari ${store?.namaToko ?? "toko lokal"} di Mall ku.` }; }
export default async function StorePage({ params }: { params: Promise<Params> }) { const { slug } = await params; const store = await prisma.tokoProfile.findUnique({ where: { slug }, include: { listingMp: { where: { status: "AKTIF", stokTampil: { gt: 0 } }, include: { toko: { select: { id: true, namaToko: true, slug: true, kabupatenKota: true } }, kategoriProduk: { select: { nama: true, slug: true } } }, orderBy: { terjual: "desc" } } } }); if (!store) notFound(); return <MarketplaceShell><main className="mx-auto max-w-[1400px] px-4 py-8 md:px-8"><section className="overflow-hidden rounded-3xl border border-[#dce4e8] bg-white"><div className="h-32 bg-[#173b68] md:h-44" /><div className="relative px-5 pb-6 md:px-8"><div className="-mt-10 flex h-20 w-20 items-center justify-center rounded-2xl border-4 border-white bg-[#fff0ef] text-[#e53935] shadow-md"><Store className="h-8 w-8" /></div><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-2xl font-extrabold text-[#26343f] md:text-3xl">{store.namaToko}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-[#82919a]"><MapPin className="h-4 w-4 text-[#e53935]" />{store.alamatLengkap}, {store.kabupatenKota}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-[#53616d]">{store.deskripsi || "Mitra toko lokal Mall ku."}</p></div><div className="flex gap-2 text-xs font-semibold text-[#53616d]"><span className="rounded-xl bg-[#f7f9fa] px-3 py-2"><Truck className="mr-1 inline h-4 w-4 text-[#168bc3]" />{store.metodePengirimanDiDukung.length ? "Pengiriman tersedia" : "Atur pengiriman"}</span><span className="rounded-xl bg-[#f7f9fa] px-3 py-2">{store.listingMp.length} produk</span></div></div></div></section><div className="mt-10 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#168bc3]">Etalase toko</p><h2 className="mt-1 text-2xl font-extrabold text-[#26343f]">Semua produk</h2></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{store.listingMp.map((product) => <ProductCard key={product.id} product={{ ...product, hargaJual: Number(product.hargaJual) }} />)}</div></main></MarketplaceShell>; }
