"use client";

import { useEffect, useState } from "react";
import { Check, Eye, X } from "lucide-react";

type Account = { id: string; name: string | null; email: string; role: string; statusAkun: string; telepon: string | null; tokoProfile?: Profile | null; distributorProfile?: Profile | null };
type Profile = { namaToko?: string; namaUsaha?: string; alamatLengkap: string; provinsi: string; kabupatenKota: string; kecamatan: string; desa?: string | null; kodePos?: string | null; noNib?: string | null; noNpwp?: string | null; dokumenNibUrl?: string | null; dokumenNpwpUrl?: string | null; gudang: unknown[]; rekening: unknown[] };

export default function AdminAkunPage() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [filter, setFilter] = useState("ALL");
  const [selected, setSelected] = useState<Account | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/akun").then((response) => response.json()).then(setAccounts).catch(() => setMessage("Data akun belum dapat dimuat.")); }, []);
  const updateStatus = async (account: Account, statusAkun: string) => { if (!window.confirm(`Apakah Anda yakin ingin mengubah status akun ${account.email} menjadi ${statusAkun}?`)) return; const response = await fetch("/api/admin/akun", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: account.id, statusAkun }) }); if (response.ok) { setAccounts((current) => current.map((item) => item.id === account.id ? { ...item, statusAkun } : item)); setSelected(null); setMessage(`Status akun ${account.email} diperbarui.`); } };
  const visible = filter === "ALL" ? accounts : accounts.filter((account) => account.statusAkun === filter);
  return <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-sky-600">Akun</p><h1 className="mt-2 text-2xl font-extrabold text-slate-800">Kelola Akun Mitra</h1><p className="mt-1 text-sm text-slate-500">Review profil, alamat, dokumen legalitas, dan rekening sebelum approval.</p></div>{message && <div className="rounded-lg border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800">{message}</div>}<div className="flex flex-wrap gap-2">{[["ALL", "Semua"], ["MENUNGGU_VERIFIKASI", "Menunggu Review"], ["AKTIF", "Aktif"], ["DITOLAK", "Ditolak"], ["NONAKTIF", "Nonaktif"]].map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${filter === value ? "border-slate-900 bg-slate-900 text-white" : "border-slate-200 bg-white text-slate-600"}`}>{label}</button>)}</div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100 text-slate-700"><tr><th className="px-4 py-3">Nama Usaha</th><th className="px-4 py-3">Tipe</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody>{visible.map((account) => { const profile = account.tokoProfile || account.distributorProfile; return <tr key={account.id} className="border-t border-slate-200"><td className="px-4 py-3 font-semibold text-slate-700">{profile?.namaToko || profile?.namaUsaha || "Belum dilengkapi"}</td><td className="px-4 py-3 text-slate-600">{account.role}</td><td className="px-4 py-3 text-slate-600">{account.email}</td><td className="px-4 py-3"><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold text-amber-700">{account.statusAkun}</span></td><td className="px-4 py-3"><button onClick={() => setSelected(account)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-600"><Eye className="h-3.5 w-3.5" /> Detail</button></td></tr>; })}</tbody></table></div>{selected && <ReviewDrawer account={selected} onClose={() => setSelected(null)} onStatus={updateStatus} />}</div>;
}

function ReviewDrawer({ account, onClose, onStatus }: { account: Account; onClose: () => void; onStatus: (account: Account, status: string) => void }) { const profile = account.tokoProfile || account.distributorProfile; return <div className="fixed inset-0 z-50 bg-slate-900/40"><button className="absolute inset-0" onClick={onClose} aria-label="Tutup detail" /><aside className="absolute right-0 top-0 h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-slate-800">Review Akun {account.role}</h2><button onClick={onClose} aria-label="Tutup"><X className="h-5 w-5" /></button></div><div className="mt-6 space-y-5 text-sm"><Info title="Akun" value={`${account.name || "-"} · ${account.email} · ${account.telepon || "-"}`} /><Info title="Alamat Utama" value={`${profile?.alamatLengkap || "-"}, ${profile?.desa || "-"}, ${profile?.kecamatan || "-"}, ${profile?.kabupatenKota || "-"}, ${profile?.provinsi || "-"} ${profile?.kodePos || ""}`} /><Info title="Dokumen" value={`NIB: ${profile?.noNib || "-"} · File NIB: ${profile?.dokumenNibUrl ? "Tersedia" : "-"} · NPWP: ${profile?.noNpwp || "-"} · File NPWP: ${profile?.dokumenNpwpUrl ? "Tersedia" : "-"}`} /><Info title="Gudang & Rekening" value={`${profile?.gudang.length || 0} gudang · ${profile?.rekening.length || 0} rekening`} /><div className="flex gap-2 border-t pt-5"><button onClick={() => onStatus(account, "AKTIF")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white"><Check className="h-4 w-4" /> Approve</button><button onClick={() => onStatus(account, "DITOLAK")} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-bold text-white">Tolak</button></div></div></aside></div>; }
function Info({ title, value }: { title: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{title}</p><p className="mt-1 text-slate-700">{value}</p></div>; }
